{% set name = "jaxopt" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d82e2f3d2b7da8a90e537f28686e0c27f6120fc6fb0e2ffed54a528ffaa174b

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - absl-py
    - jaxlib >=0.1.69
    - jax >=0.2.18
    - numpy >=1.18.4
    - scipy >=1.0.0
    - matplotlib-base >=2.0.1

test:
  imports:
    - {{ name|lower }}

about:
  home: https://jaxopt.github.io/stable/
  summary: Hardware accelerated, batchable and differentiable optimizers in JAX
  description: |
    Hardware accelerated, batchable and differentiable optimizers in JAX  
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://jaxopt.github.io/stable/
  dev_url: https://github.com/google/jaxopt

extra:
  recipe-maintainers:
    - dirmeier
