{% set name = "jaxopt" %}
{% set version = "0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 19df9cb745ee39fa27f9ba4f01bbec5b0e3a8a1f60320aff553131a5f152c9fa

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools
    - pip
  run:
    - python >=3.7
    - absl-py
    - jaxlib >=0.1.69
    - jax >=0.2.18
    - numpy >=1.18.4
    - scipy >=1.0.0
    - matplotlib-base >=2.0.1

test:
  imports:
    - {{ name|lower }}

about:
  home: https://jaxopt.github.io/stable/
  summary: Hardware accelerated, batchable and differentiable optimizers in JAX
  description: |
    Hardware accelerated, batchable and differentiable optimizers in JAX  
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://jaxopt.github.io/stable/
  dev_url: https://github.com/google/jaxopt

extra:
  recipe-maintainers:
    - dirmeier
